version: '2.1'
services:
  app:
    build: .
    environment:
      MYAPP_DATABASE_HOST: mongodb   
      MYAPP_WEB_PORT: 8080
    links:
      - mongodb
    depends_on:
      mongodb:
        condition: service_healthy

    ports:
      - 3000:8080
  mongodb:
     image: healthcheck/mongo
 
